services:
  postgres:
    image: postgres:17.3
    container_name: book-shelf-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT_INTERNAL}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [ net ]
  migrations:
    container_name: migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
    build:
      context: .
      dockerfile: Dockerfile.migrations
    networks: [ net ]
  service:
    container_name: book-shelf-service
    image: book-shelf-service:latest
    environment:
      DB_URL: ${DB_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      TOKEN_TTL: ${TOKEN_TTL}
      HTTP_PORT: ${HTTP_PORT}
    build:
      context: .
      dockerfile: Dockerfile
      target: service
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: [ "/service" ]
    networks: [ net ]

volumes:
  postgres_data:

networks:
  net: