apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-shelf
  namespace: book-shelf
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
    - host: kosarev.app
      http:
        paths:
          - path: /api/book-shelf(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: book-shelf
                port:
                  number: 80
  tls:
    - hosts:
        - kosarev.app