apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-shelf
  namespace: book-shelf
spec:
  ingressClassName: nginx
  rules:
    - host: api.kosarev.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-shelf
                port:
                  number: 80